apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: backend-deploy-1
  targetCPUUtilizationPercentage: 25
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 25
