apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deploy
    version: v2
  name: backend-deploy-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deploy
      version: v2
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: backend-deploy
        tier: backend
        version: v2
    spec:
      containers:
      - image: dennismila/backend-void:1.2
        name: void-backend
        ports:
        - containerPort: 9080
        env:
        - name: DB_ADMINUSER
          valueFrom:
            secretKeyRef:
              name: void-secret
              key: DB_ADMINUSER
        - name: DB_ADMINPWD
          valueFrom:
            secretKeyRef:
              name: void-secret
              key: DB_ADMINPWD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: void-config
              key: DB_HOST
        - name: DB_PORT 
          valueFrom:
            configMapKeyRef:
              name: void-config
              key: DB_PORT
        - name: R_HOST
          valueFrom:
            configMapKeyRef:
              name: void-config
              key: R_HOST
        - name: R_PORT
          valueFrom:
            configMapKeyRef:
              name: void-config
              key: R_PORT
status: {}
