apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"frontend-deploy","version":"v1"},"name":"frontend-deploy","namespace":"thevoid"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"frontend-deploy","version":"v1"}},"strategy":{},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"true"},"creationTimestamp":null,"labels":{"app":"frontend-deploy","version":"v1"}},"spec":{"containers":[{"env":[{"name":"BACKEND_URL","valueFrom":{"configMapKeyRef":{"key":"BACKEND_URL","name":"void-config"}}}],"image":"dennismila/void-frontend:1.1","name":"void-frontend","ports":[{"containerPort":3000}],"resources":{}}]}}},"status":{}}
  labels:
    app: frontend-deploy
    version: v2
  name: frontend-deploy-canary
  namespace: thevoid
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend-deploy
      version: v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: frontend-deploy
        version: v2
    spec:
      containers:
      - env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              key: BACKEND_URL
              name: void-config
        image: dennismila/void-frontend:1.2
        imagePullPolicy: IfNotPresent
        name: void-frontend
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
             cpu: 125m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
