apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: frontend-deploy-2
  targetCPUUtilizationPercentage: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 20
