apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: thevoid
  annotations:
    metric-config.object.istio-requests-total.prometheus/per-replica: "true"
    metric-config.object.istio-requests-total.prometheus/query: |
      sum(
        rate(
          istio_requests_total{
            destination_service=~"frontend-service.thevoid.svc.cluster.local"
          }[1m]
        )
      ) /
      count(
        count(
          container_memory_usage_bytes{
            namespace="thevoid",
            pod_name=~"frontend.*"
          }
        ) by (pod_name)
      )
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: frontend-deploy
  targetCPUUtilizationPercentage: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 10
